package ooxml
type WordSchema  struct {
	ClientData CT_ClientData  `xml:"ClientData"`
}
type CT_ClientData struct{
	MoveWithCells string  `xml:"MoveWithCells"`
	SizeWithCells string  `xml:"SizeWithCells"`
	Anchor string  `xml:"Anchor"`
	Locked string  `xml:"Locked"`
	DefaultSize string  `xml:"DefaultSize"`
	PrintObject string  `xml:"PrintObject"`
	Disabled string  `xml:"Disabled"`
	AutoFill string  `xml:"AutoFill"`
	AutoLine string  `xml:"AutoLine"`
	AutoPict string  `xml:"AutoPict"`
	FmlaMacro string  `xml:"FmlaMacro"`
	TextHAlign string  `xml:"TextHAlign"`
	TextVAlign string  `xml:"TextVAlign"`
	LockText string  `xml:"LockText"`
	JustLastX string  `xml:"JustLastX"`
	SecretEdit string  `xml:"SecretEdit"`
	Default string  `xml:"Default"`
	Help string  `xml:"Help"`
	Cancel string  `xml:"Cancel"`
	Dismiss string  `xml:"Dismiss"`
	Accel string  `xml:"Accel"`
	Accel2 string  `xml:"Accel2"`
	Row string  `xml:"Row"`
	Column string  `xml:"Column"`
	Visible string  `xml:"Visible"`
	RowHidden string  `xml:"RowHidden"`
	ColHidden string  `xml:"ColHidden"`
	VTEdit string  `xml:"VTEdit"`
	MultiLine string  `xml:"MultiLine"`
	VScroll string  `xml:"VScroll"`
	ValidIds string  `xml:"ValidIds"`
	FmlaRange string  `xml:"FmlaRange"`
	WidthMin string  `xml:"WidthMin"`
	Sel string  `xml:"Sel"`
	NoThreeD2 string  `xml:"NoThreeD2"`
	SelType string  `xml:"SelType"`
	MultiSel string  `xml:"MultiSel"`
	LCT string  `xml:"LCT"`
	ListItem string  `xml:"ListItem"`
	DropStyle string  `xml:"DropStyle"`
	Colored string  `xml:"Colored"`
	DropLines string  `xml:"DropLines"`
	Checked string  `xml:"Checked"`
	FmlaLink string  `xml:"FmlaLink"`
	FmlaPict string  `xml:"FmlaPict"`
	NoThreeD string  `xml:"NoThreeD"`
	FirstButton string  `xml:"FirstButton"`
	FmlaGroup string  `xml:"FmlaGroup"`
	Val string  `xml:"Val"`
	Min string  `xml:"Min"`
	Max string  `xml:"Max"`
	Inc string  `xml:"Inc"`
	Page string  `xml:"Page"`
	Horiz string  `xml:"Horiz"`
	Dx string  `xml:"Dx"`
	MapOCX string  `xml:"MapOCX"`
	CF ST_CF  `xml:"CF"`
	Camera string  `xml:"Camera"`
	RecalcAlways string  `xml:"RecalcAlways"`
	AutoScale string  `xml:"AutoScale"`
	DDE string  `xml:"DDE"`
	UIObj string  `xml:"UIObj"`
	ScriptText string  `xml:"ScriptText"`
	ScriptExtended string  `xml:"ScriptExtended"`
	ScriptLanguage string  `xml:"ScriptLanguage"`
	ScriptLocation string  `xml:"ScriptLocation"`
	FmlaTxbx string  `xml:"FmlaTxbx"`
	ObjectType ST_ObjectType  `xml:"ObjectType",attr`
}
